---
- name: Create a Security Group
  local_action:
    module: ec2_group
    name: "{{ item.key }}"
    description: "Security group for the {{ item.key }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      "{{ item.value.rules }}"
    rules_egress:
      "{{ item.value.rules_egress | default( [{'proto': 'all', 'cidr_ip': '0.0.0.0/0'}] ) }}"
    state: present
    tags:
      Name: "{{ item.key }}"
  with_dict: "{{ sg_settings }}"
  register: aws_ec2_sg

- name: Display Ec2 Security Group
  debug: var=aws_ec2_sg

- name: set fact security_group_name
  set_fact:
    ec2_sg_name_var: "{{ aws_ec2_sg.results.0.invocation.module_args.name }}"

- name: set fact security_group_id
  set_fact:
    ec2_sg_id_var: "{{ aws_ec2_sg.results.0.group_id }}"


