---
- name: Create a target group for alb
  local_action:
    module: elb_target_group
    name: "{{ item.value.name }}"
    protocol: "{{ item.value.protocol }}"
    port: "{{ item.value.port }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    health_check_path: "{{ item.value.healthcheck_path }}"
    state: present
    tags:
        Name: "{{ item.value.name }}"
  with_dict: "{{ elb_target_group_names }}"
  register: aws_elb_target_group

# - name: Display ALB Target Group
#   debug: var=aws_elb_target_group

- elb_application_lb:
    name: "{{ item.target_group_name }}"
    subnets: "{{ application_subnet }}"
    security_groups: "{{ elb_security_group }}"
    scheme: internal
    region: "{{ aws_region }}"
    listeners:
      - Protocol: HTTPS
        Port: 443
        DefaultActions:
          - Type: forward
            TargetGroupName: "{{ item.target_group_name }}"
        Certificates:
          - CertificateArn: "{{ elb_ssl_certificate }}"
        SslPolicy: ELBSecurityPolicy-2016-08
        Rules:
          - Conditions:
              - Field: path-pattern
                Values:
                  - '/'
            Priority: '1'
            Actions:
              - TargetGroupName: "{{ item.target_group_name }}"
                Type: forward
    tags:
        Name: "{{ item.target_group_name }}"
    state: present
  with_items:
    - "{{ aws_elb_target_group.results }}"
