---
# tasks file for RDS
- name: Create a RDS
  local_action:
    module: rds
    command: create
    instance_name: "{{ rds_instance_name }}"
    db_engine: "{{ db_engine_type }}"
    size: "{{ rds_size }}"
    instance_type: "{{ rds_instance_type }}"
    username: "{{ rds_db_username }}"
    password: "{{ rds_db_password }}"
    region: "{{ aws_region }}"
    tags:
      Environment: "{{ env }}"
      Application: "{{ application_name }}"
  register: aws_rds

- name: Display RDS
  debug: var=aws_rds
