---
- name: Create a Launch configuration for Autosclaing group
  local_action:
    module: ec2_lc
    name: "{{ ec2_asg_lc_name }}"
    region: "{{ aws_region }}"
    image_id: "{{ ec2_ami_image }}"
    key_name: "{{ ec2_keypair }}"
    security_groups: "{{ ec2_security_group_id }}"
    instance_type: "{{ ec2_instance_type }}"
    instance_profile_name : "{{ ec2_instance_profile_role }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_root_storage }}"
        delete_on_termination: true
    state: present
  register: aws_asg_lc

- name: Display Autoscaling Launch configuration
  debug: var=aws_asg_lc

- name: Set Autoscaling launch configuration name in variable
  set_fact:
    aws_asg_lc_name_var: "{{ aws_asg_lc.name}}"

- ec2_asg:
    name: "{{ ec2_asg_name }}"
    launch_config_name: "{{ aws_asg_lc_name_var }}"
    health_check_period: "{{ ec2_asg_health_check_period }}"
    health_check_type: "{{ ec2_asg_health_check_type }}"
    replace_all_instances: yes
    min_size: "{{ ec2_asg_min_size }}"
    max_size: "{{ ec2_asg_max_size }}"
    desired_capacity: "{{ ec2_asg_desired_size }}"
    region: "{{ aws_region }}"
    vpc_zone_identifier: "{{ ec2_vpc_subnet_id }}"
    tags:
      - Name: "{{ ec2_asg_name }}"
    state: present
  register: aws_ec2_asg

- name: Display Autoscaling Group
  debug: var=aws_ec2_asg

